
def accountMaddress(data):
    xml_entries = "".join(f"""
            <AccountMAddress
                Address1="{row['Address1']}"
                Address2="{row['Address2']}"
                DistrictID="{row['DistrictID']}"
                District="{row['District']}"
                StateID="{row['StateID']}"
                State="{row['State']}"
                CountryID="{row['CountryID']}"
                Country="{row['Country']}"
                Pincode="{row['Pincode']}"
                Status="{row['Status']}"
                CreatedBy="{row['CreatedBy']}"
                UpdatedBy="{row['UpdatedBy']}"
                ADDT1="{row['ADDT1']}"
                ADDT2="{row['ADDT2']}"
                ADDT3="{row['ADDT3']}"
                ADDT4="{row['ADDT4']}"
                ADDT5="{row['ADDT5']}"
                ADDI1="{row['ADDI1']}"
                ADDI2="{row['ADDI2']}"
                ADDI3="{row['ADDI3']}"
                ADDI4="{row['ADDI4']}"
                ADDI5="{row['ADDI5']}"
                ADDD1="{row['ADDD1']}"
                ADDD2="{row['ADDD2']}"
                ADDD3="{row['ADDD3']}"
                ADDD4="{row['ADDD4']}"
                ADDD5="{row['ADDD5']}"
                ADDDT1="{row['ADDDT1']}"
                ADDDT2="{row['ADDDT2']}"
                ADDDT3="{row['ADDDT3']}"
                ADDDT4="{row['ADDDT4']}"
                ADDDT5="{row['ADDDT5']}"
                ADDB1="{row['ADDB1']}"
                ADDB2="{row['ADDB2']}"
                ADDB3="{row['ADDB3']}"
                ADDB4="{row['ADDB4']}"
                ADDB5="{row['ADDB5']}"
                ActiveStatus="{row['ActiveStatus']}" />
        """ for row in data)
    full_xml = f"<AccountMAddress>{xml_entries}</AccountMAddress>"
    return full_xml
